import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black font-serif `}
      >
        {/* <nav>
          <ul>
            <li><Link href="/">Home</Link></li>
            <li><Link href="/skripsi">Skripsi</Link></li>
            <li><Link href="/tesis">Tesis</Link></li>
            <li><Link href="/spss">SPSS</Link></li>
          </ul>
        </nav> */}
        {children}
      </body>
    </html>
  );
}
